spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/talent2
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

      initialSize: 10
      maxActive: 20
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      validationQuery: SELECT 1
      validation-query-timeout: 500
      filters: stat,wall

      stat-view-servlet.enabled: true
      stat-view-servlet.url-pattern: /druid/*
      stat-view-servlet.reset-enable: true
      stat-view-servlet.login-username: admin
      stat-view-servlet.login-password: admin



mybatis:
  mapper-locations: classpath:mappers/*.xml
#  type-aliases-package: "com.qiao.train.po

